manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: gerritvreeman
      url-base: https://github.com/gerritvreeman
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: urchin-zmk-module
      remote: gerritvreeman
      revision: main
  self:
    path: config
